# File: docker-compose.yml

version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  frontend:
    image: nginx:alpine
    container_name: frontend-ui
    ports:
      - "5500:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
